In [2]:
import numpy as np
import math
import scipy.fft as fft

In [19]:
# x=[10,20,30,40,50,60,70,80,90,10]
x=[1,2]
x_tilde = x.copy()
x_tilde.reverse()

print(f'x\t={x}')
print(f'x_tilde\t={x_tilde}')


x	=[1, 2]
x_tilde	=[2, 1]


In [22]:
np.round(fft.dct(x, norm='ortho'),2)

array([ 2.12, -0.71])

In [23]:
np.round(fft.dct(x_tilde, norm='ortho'),2)

array([2.12, 0.71])

In [57]:
def dct_verbose(x):
    N = len(x)
    c0_norm = np.sqrt(1/N)
    ck_norm = np.sqrt(2/N)

    print(f'x={x} N={N}')
    print(f'c0_norm={c0_norm:.2}')
    print(f'ck_norm={ck_norm:.2}')
    print()
    
    C = np.zeros(N)
    C[0] = c0_norm * np.sum(x)

    m = np.arange(0,N,1)
    for k in range(1,N):
        print(f'k={k}')
        base = np.cos(math.pi*k*(m+(1/2))/N)
        #base=np.flip(base)
        print(f'x*base={x}*{base}')
        print(f'sum(x*base)={np.sum(x*base)}')
        
        #C[k] = ck_norm * np.sum(x * np.cos(math.pi*k*(m+(1/2))/N))
        C[k] = ck_norm * np.sum(x*base)
    
    return C

dct_verbose([1,2,3,4])

x=[1, 2, 3, 4] N=4
c0_norm=0.5
ck_norm=0.71

k=1
x*base=[1, 2, 3, 4]*[ 0.92387953  0.38268343 -0.38268343 -0.92387953]
sum(x*base)=-3.1543220298989496
k=2
x*base=[1, 2, 3, 4]*[ 0.70710678 -0.70710678 -0.70710678  0.70710678]
sum(x*base)=-8.881784197001252e-16
k=3
x*base=[1, 2, 3, 4]*[ 0.38268343 -0.92387953  0.92387953 -0.38268343]
sum(x*base)=-0.22417076458398388


array([ 5.00000000e+00, -2.23044250e+00, -6.28036983e-16, -1.58512668e-01])

In [43]:
dct_verbose(x_tilde)

x=[2, 1] N=2
c0_norm=0.71
ck_norm=1.0

k=0
x*base=[2, 1]*[ 0.70710678 -0.70710678]
sum(x*base)=0.7071067811865477


array([2.12132034, 0.70710678])