In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import scipy.fft as spfft

In [15]:
def cria_matriz_circulante(h):
    N = len(h)
    Mh = np.zeros((N,N))
    h_reversed = np.flip(h)
    for row in range(N):
        Mh[row] = np.roll(h_reversed,row+1)
    return Mh

h = np.array([1,5,7,2])
My = cria_matriz_circulante(h)
My

array([[1., 2., 7., 5.],
       [5., 1., 2., 7.],
       [7., 5., 1., 2.],
       [2., 7., 5., 1.]])

In [8]:
def conv1(x,y):
    N=len(x)
    w = np.zeros(N)
    for n in range(N):
        for k in range(N):
            w[n] += x[k] * y[n-k]
            
    return w

def conv2(x,My):
    return np.inner(My,x)

x = np.array( [1, -1, 1, 2])

In [5]:
x

array([ 1, -1,  1,  2])

In [7]:
conv1(x,h)

array([16., 20.,  7.,  2.])

In [16]:
conv2(x,My)

array([16., 20.,  7.,  2.])

In [23]:
def reversao_temporal(h):
    N = len(h)
    h_linha = np.zeros(N)
    for k in range(N):
        h_linha[k] = np.conjugate(h[-k])
    return h_linha

h_linha = reversao_temporal(h)
h_linha

array([1., 2., 7., 5.])

In [22]:
cria_matriz_circulante(h_linha)

array([[1., 5., 7., 2.],
       [2., 1., 5., 7.],
       [7., 2., 1., 5.],
       [5., 7., 2., 1.]])