In [1]:
import numpy as np
import math

In [3]:

x=[1,2,3,4,5]
X = np.fft.fft(x)
X    

array([15. +0.j        , -2.5+3.4409548j , -2.5+0.81229924j,
       -2.5-0.81229924j, -2.5-3.4409548j ])

In [6]:
y = [2,3,4,5,1]
Y = np.fft.fft(y)
Y

array([15.        +0.j        , -4.04508497-1.31432778j,
        1.54508497-2.12662702j,  1.54508497+2.12662702j,
       -4.04508497+1.31432778j])

In [10]:
X*(np.exp(1j*2*math.pi*))

array([15. -3.67394040e-15j, -2.5+3.44095480e+00j, -2.5+8.12299241e-01j,
       -2.5-8.12299241e-01j, -2.5-3.44095480e+00j])

In [14]:
np.isclose(X[1],Y[1])

False

In [15]:
np.isclose(X[1]*np.exp(1j*2*math.pi/5),Y[1])

True

In [ ]:
np.isclose(X[2]*np.exp(1j*2*math.pi/5),Y[1])