In [2]:
import math
import numpy as np

In [30]:
N=4
t = np.arange(0,1,1/N)
E = np.exp(1j * 2 * math.pi * t)
def E(k):
    return np.exp(1j * 2 * math.pi * t * k)

S = [E(0), E(1), E(2), E(3)]

In [9]:
S = np.array([[1,1,1,1],[1,1j,-1,-1j],[1,-1,1,-1],[1,-1j,-1,1j]])


In [10]:
e0 = np.array([1,0,0,0], dtype=complex)
e1 = np.array([0,1,0,0], dtype=complex)
e2 = np.array([0,0,1,0], dtype=complex)
e3 = np.array([0,0,0,1], dtype=complex)

A equação 1.34 (exemplo 1.23 da página 38) apresenta como encontrar os coeficientes da combinação linear para decompor um sinal x.

$$x = \sum_{k=0}^{N-1} \frac{(x,E_{N,k})}{(E_{N,k}, E_{N,k)}} E_{N,k}$$
como $(E_{N,k}, E_{N,k})=N$, então :

$$x = \frac{1}{N} \sum_{k=0}^{N-1} (x,E_{N,k}) E_{N,k}$$

Continuando a Definição de DFT (Definiçao 2.1 na página 79) apresenta a decomposição de uma maneira ligeiramente diferente. Sem a divisão por $N$. Em outras palavras $X_k = N * $ coeficiente anterior.

$$X_k = (x,E_{N,k})$$


In [35]:

x = e4
# Como se trata do espaço dos complexos, precisamos dizer para o numpy para conjungar a segunda parte
Xk0 = np.inner(x, np.conjugate(S[0])) 
Xk1 = np.inner(x, np.conjugate(S[1])) 
Xk2 = np.inner(x, np.conjugate(S[2])) 
Xk3 = np.inner(x, np.conjugate(S[3])) 

print(f'Xk=({Xk0},{Xk1},{Xk2},{Xk3})')
print(f'magnitude({abs(Xk0)},{abs(Xk1)},{abs(Xk2)},{abs(Xk3)})')


NameError: name 'e4' is not defined

In [50]:
N=10
t = np.arange(0,1,1/N)
E = np.exp(1j * 2 * math.pi * t)
def E(k):
    return np.exp(1j * 2 * math.pi * t * k)

S = []
for e in range(N):
    S.append(np.conjugate(E(e)))


for s in S:
    print(abs(s))


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
abs(Xk1)

1.0