In [1]:
import numpy as np
import math

In [2]:
def dft2d(A):
    m, n = A.shape
    Ahat = np.zeros((m,n), dtype='complex')
    for k in range(m):
        for l in range(n):
            for r in range(m):
                for s in range(n):
                    Ahat[k][l] += A[r][s] * np.exp(-1j*2*math.pi*(k*r/m + l*s/n))
    return Ahat
                    
                    
def idft2d(Ahat):
    m, n = Ahat.shape
    A = np.zeros((m,n), dtype='complex')
    for k in range(m):
        for l in range(n):
            for r in range(m):
                for s in range(n):
                    A[r][s] += Ahat[k][l] * np.exp(1j*2*math.pi*(k*r/m + l*s/n))
    A = (1/(m*n)) * A
    return A





In [3]:
A = np.array([1, -1, 2, 0]).reshape((2,2))
A


array([[ 1, -1],
       [ 2,  0]])

In [4]:
np.fft.fft2(A)

array([[ 2.+0.j,  4.+0.j],
       [-2.+0.j,  0.+0.j]])

In [9]:
np.fft.ifft2(np.fft.fft2(A))

array([[ 1.+0.j, -1.+0.j],
       [ 2.+0.j,  0.+0.j]])

In [17]:
np.round(np.fft.ifft2(dft2d(A)))

array([[ 1.-0.j, -1.-0.j],
       [ 2.+0.j,  0.+0.j]])

In [19]:
np.round(idft2d(dft2d(A)))

array([[ 1.-0.j, -1.+0.j],
       [ 2.+0.j, -0.+0.j]])

In [21]:
np.round(idft2d(np.fft.fft2(A)))

array([[ 1.+0.j, -1.+0.j],
       [ 2.-0.j,  0.+0.j]])

In [27]:
A[1][1]

0

In [5]:
res = np.fft.fft2(A)
for i in range(2):
    for j in range(2):
        print(f'i={i} j={j} {res[i][j]} ')

i=0 j=0 (2+0j) 
i=0 j=1 (4+0j) 
i=1 j=0 (-2+0j) 
i=1 j=1 0j 


In [7]:
res = np.round(dft2d(A))
for i in range(2):
    for j in range(2):
        print(f'i={i} j={j} {res[i][j]} ')

i=0 j=0 (2+0j) 
i=0 j=1 (4+0j) 
i=1 j=0 (-2-0j) 
i=1 j=1 -0j 
