In [1]:
import math as m
import numpy as np


In [7]:
E_n4 = np.array([[1,1,1,1],[1,1j,-1,-1j],[1,-1,1,-1],[1,-1j,-1,1j]])
E_n4

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j]])

In [37]:
E_n4_barra = np.array([[1,1,1,1],[1,-1j,-1,1j],[1,-1,1,-1],[1,1j,-1,-1j]])
E_n4_barra

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j, -0.-1.j, -1.+0.j,  0.+1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j, -0.-1.j]])

In [12]:
x_n = np.array([1,2,0,-1])
x_n

array([ 1,  2,  0, -1])

In [38]:
x_n * E_n4_barra[0]

array([ 1.+0.j,  2.+0.j,  0.+0.j, -1.+0.j])

In [39]:
x_n * E_n4_barra

array([[ 1.+0.j,  2.+0.j,  0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.-2.j, -0.+0.j, -0.-1.j],
       [ 1.+0.j, -2.+0.j,  0.+0.j,  1.-0.j],
       [ 1.+0.j,  0.+2.j, -0.+0.j,  0.+1.j]])

In [40]:
X_0 = np.sum(x_n * E_n4_barra[0])
X_0

(2+0j)

In [41]:
X_n = x_n * E_n4_barra
X_n

array([[ 1.+0.j,  2.+0.j,  0.+0.j, -1.+0.j],
       [ 1.+0.j,  0.-2.j, -0.+0.j, -0.-1.j],
       [ 1.+0.j, -2.+0.j,  0.+0.j,  1.-0.j],
       [ 1.+0.j,  0.+2.j, -0.+0.j,  0.+1.j]])

In [22]:
np.sum(X_n[3])

(1-3j)

In [42]:
X_n=np.sum(X_n, axis=1)
X_n

array([2.+0.j, 1.-3.j, 0.+0.j, 1.+3.j])

In [45]:
# tentando rodar a IDFT
np.sum(X_n * E_n4, axis=1)/4


array([ 1.+0.j,  2.+0.j,  0.+0.j, -1.+0.j])

In [50]:
# e a energia?
do sinal original
np.linalg.norm(x_n)**2

5.999999999999999

In [51]:
4 * abs(X_n)**2

array([16., 40.,  0., 40.])

-----
Tentando agora a IDFT

In [30]:
W_n = np.array([3,1+1j,1,1-1j])
W_n

array([3.+0.j, 1.+1.j, 1.+0.j, 1.-1.j])

In [36]:
w_n = np.sum(W_n * E_n4, axis=1)/4
w_n

array([1.5+0.j, 0. +0.j, 0.5+0.j, 1. +0.j])

In [48]:
# Tentando rodar a DFT
np.sum(w_n * E_n4_barra, axis=1)

array([3.+0.j, 1.+1.j, 1.+0.j, 1.-1.j])